# Generated by Django 4.1 on 2024-05-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("poet", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("tags", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Poema",
        ),
    ]
